<a href="https://colab.research.google.com/github/rameshbabulakshmanan84/AI-Day---Knowledge-Graph/blob/master/Pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
#Unitialized
x=torch.empty(5,3)

In [4]:
print(x)

tensor([[8.0396e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


In [6]:
#Random initialized array
x=torch.rand(5,3)
x

tensor([[0.2361, 0.6174, 0.3550],
        [0.3480, 0.0360, 0.8278],
        [0.5571, 0.0116, 0.5263],
        [0.7206, 0.0782, 0.2254],
        [0.0469, 0.5206, 0.8852]])

In [7]:
x=torch.zeros((5,3),dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [10]:
#initialize the torch
x=torch.tensor([5,3])
x

tensor([5, 3])

In [11]:
x=x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [13]:
x=torch.randn_like(x,dtype=torch.float)
x

tensor([[ 0.7012,  0.9786,  0.3576],
        [ 0.2119, -1.1724,  1.3245],
        [-1.0249,  0.5118,  1.7047],
        [-2.0711,  0.9770, -2.0021],
        [-1.5603,  0.7013, -0.2785]])

In [14]:
y=torch.randn(5,3)

In [15]:
print(x+y)

tensor([[ 1.1189, -0.0756,  0.5250],
        [-0.0471, -1.1110,  1.2267],
        [ 0.1794, -1.1047,  2.5203],
        [-2.7208,  2.3825, -2.4673],
        [-0.2277,  0.7173,  0.1629]])


In [17]:
print(torch.add(x,y))

tensor([[ 1.1189, -0.0756,  0.5250],
        [-0.0471, -1.1110,  1.2267],
        [ 0.1794, -1.1047,  2.5203],
        [-2.7208,  2.3825, -2.4673],
        [-0.2277,  0.7173,  0.1629]])


In [21]:
#Resize a tensor
x=torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8)
z

tensor([[ 0.2082, -0.0705, -1.0272,  0.6154, -0.0296,  0.1003, -0.5888, -1.4483],
        [ 0.9277,  1.0296,  0.1193, -1.9788, -0.9216,  1.4849,  0.7876,  0.2992]])

In [22]:
#create a tensor and set req_grad=True
x=torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
